# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Axel Lárusson
title: Software Engineer
email: axelminn@email.com
# website: www.github.com/axelminn

# Social links
# twitter_username: facespics
github_username:  axelminn
# dribbble_username: jekyll
facebook_username: axel.larusson
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: axellarusson
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profil.jpg
about_content: | # this will include new lines to allow paragraphs

  Software Engineer inmy second year ofmy master’s studies at KTH in Stockholm. I also have 4 years working experience as a software engineer. Looking for a new
  challenge where I can further enhance my skills and widen my knowledge in the field of software development.
  
  # Hi, my name's Brett and I'm a senior network system administrator. As well as administrating systems I also have experience making software and web apps. I have worked at a number of companies gaining teamwork and leadership skills.
  # I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Quality time with my family
   - Football
   - Movies
   - Gaming
   - Knitting

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
